### ISSUE TITLE
FR: Be able to sort entities based on timestamp?

### ISSUE THREAD

**Issue by danielbrunt57** [thomasloven/lovelace-badge-card#15]
I would like to be able to have these badges arranged by "next occuring" (if that makes sense)...

![image](https://github.com/thomasloven/lovelace-badge-card/assets/49846893/c8c7792f-2a7d-4437-be59-1301ad9a3a6f)

So as of the current time now, the order would be Next Solar Midnight, Next Sunrise, Next Solar Noon, Next sunset and I'd like the order to be:
![image](https://github.com/thomasloven/lovelace-badge-card/assets/49846893/c77178c7-75d0-4317-a0fc-33890b7cd883)

**Comment by ildar170975** [comment]
Try using auto-entities. 
Go to corr. auto-entities Community thread.

**Comment by danielbrunt57** [comment]
> Try using auto-entities.

Thanks, got it working.  I had to modify my templated entities and added a timestamp of the sun.sun attribute since my state is just HH:MM with nothing else useful to sort by.  last_updated, last_changed and last_triggered were useless!

![image](https://github.com/thomasloven/lovelace-badge-card/assets/49846893/25ac0c51-f0f8-4bc8-ba23-2beb270c406e)

```
type: custom:auto-entities
card: 
  type: custom:badge-card
card_param: badges
entities:
  - entity: sensor.time
  - entity: sensor.period_of_day
filter: 
  include:
    - entity_id: sensor.next_s*
      sort:
        method: attribute
        attribute: timestamp
        reverse: false
```
```
  - name: "Next Solar Midnight"
    unique_id: next_solar_midnight
    state: '{{ as_timestamp(state_attr("sun.sun","next_midnight")) | timestamp_custom("%H:%M", true)}}'
    icon: mdi:weather-sunset-up
    attributes:
      timestamp: '{{ as_timestamp(state_attr("sun.sun","next_midnight")) }}'
    
  - name: "Next Dawn"
    unique_id: next_dawn
    state: '{{ as_timestamp(state_attr("sun.sun","next_dawn"),0) | timestamp_custom("%H:%M", true)}}'
    icon: mdi:weather-sunset-up
    attributes:
      timestamp: '{{ as_timestamp(state_attr("sun.sun","next_midnight")) }}'
  
  - name: "Next Sunrise"
    unique_id: next_sunrise
    state: '{{ as_timestamp(state_attr("sun.sun","next_rising"),0) | timestamp_custom("%H:%M", true) }}'
    icon: mdi:weather-sunset-up
    attributes:
      timestamp: '{{ as_timestamp(state_attr("sun.sun","next_rising")) }}'

  - name: "Next Solar Noon"
    unique_id: next_solar_noon
    state: '{{ as_timestamp(state_attr("sun.sun","next_noon"),0) | timestamp_custom("%H:%M", true)}}'
    icon: mdi:weather-sunset-up
    attributes:
      timestamp: '{{ as_timestamp(state_attr("sun.sun","next_noon")) }}'
    
  - name: "Next Sunset"
    unique_id: next_sunset
    state: '{{ as_timestamp(state_attr("sun.sun","next_setting"),0) | timestamp_custom("%H:%M", true) }}'
    icon: mdi:weather-sunset-down  
    attributes:
      timestamp: '{{ as_timestamp(state_attr("sun.sun","next_setting")) }}'

  - name: "Next Dusk"
    unique_id: next_dusk
    state: '{{ as_timestamp(state_attr("sun.sun","next_dusk"),0) | timestamp_custom("%H:%M", true)}}'
    icon: mdi:weather-sunset-up
    attributes:
      timestamp: '{{ as_timestamp(state_attr("sun.sun","next_dusk")) }}'
```
