### ISSUE TITLE
Home Assistant mobile app reload problem

### ISSUE THREAD

**Issue by Gloomyeye** [thomasloven/lovelace-badge-card#18]
Hello,

I use the following code to show only relevant badges with an entity filter card. However, if I reload the page with the home assistant app on my mobile device (Apple iPhone 14 Pro) by pulling down the page, then the entity card vanishes. 

```
type: entity-filter
entities:
  - entity: binary_sensor.aqara_vibration_mailbox
    name: Postkasten
    state_filter:
      - 'on'
show_empty: false
card:
  type: custom:badge-card
```
