### ISSUE TITLE
Card style background

### ISSUE THREAD

**Issue by nottledim** [thomasloven/lovelace-badge-card#19]
I'm not sure if this is an issue or a request for help.

I've got a vertical-stack containing a number of entities cards plus two custom:badge-cards with their lists of badges.

```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity:
    ...
 - type: custom:badge-card
     badges:
       - entity:
```

All the entities cards in have a typical card style background (black border, curved corners and lighter background).  The badge cards are displayed without a background as they would be if the badges where at the top of the dashboard.

Is there a way to give style the badge card so it has the typical card background as a container for the badges?
My thinking is there should be a "card style" option but there may be other ways.
