### ISSUE TITLE
Adding a title to the card

### ISSUE THREAD

**Issue by miniil** [thomasloven/lovelace-badge-card#24]
Hi
It could be good if title can be added the card

**Comment by jordanwalster** [comment]
I'm not sure if you've worked this out yet or not but you can do this by using something like this:
```
type: custom:badge-card
badges:
  - entity: sensor.time
    show_name: true
```

**Comment by ildar170975** [comment]
> you can do this by using something like this:

Sorry, but OP probably meant a TITLE of the card, not a name of a particular badge.

**Comment by jordanwalster** [comment]
Something more like _this_ then?

```
type: custom:badge-card
badges:
  - entity: sensor.time
    show_name: true
    name: Current Time
```
Unless I am misunderstanding?
