### ISSUE TITLE
Custom element doesn't exist: hui-badge-card-card.

### ISSUE THREAD

**Issue by genem2** [thomasloven/lovelace-badge-card#3]
Hi.  
I'm having trouble trying to show a badge for media players that are playing.
```
type: 'custom:auto-entities'
show_empty: false
filter:
  include:
    - domain: media_player
  exclude:
    - state: paused
    - state: standby
card:
  type: badge-card
```
Results in:
```
Custom element doesn't exist: hui-badge-card-card.
entities:
  - entity: media_player.villages_s_echo_dot
  - entity: media_player.recroom
type: badge-card
```
I'm not seeing any dependencies mentioned in your documentation and installed the badge-card using the HACS.
Changing type: badge-card to glance works (I guess I could use that).
Badges for media player appear to work if I put them in the std badges location at the top.

EDIT:  sorry...
```
arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.19.107-Unraid
python_version | 3.8.3
timezone | America/Los_Angeles
version | 0.113.3
virtualenv | false


```

**Comment by genem2** [comment]
I accidentally noticed **hui-element** in the store today and was hoping this might help. 
Maybe it did to some extent.  I installed it, and not get a different error:

```
i.setConfig is not a function
type: 'custom:auto-entities'
show_empty: false
filter:
  include:
    - domain: media_player
  exclude:
    - state: paused
    - state: standby
card:
  type: badge-card
```
