### ISSUE TITLE
HA 2021.6: TypeError: null is not an object (evaluating 'this.shadowRoot.querySelector')

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-badge-card#6]
please have a look at this error after updating to HA 2021.6:

<img width="493" alt="Schermafbeelding 2021-05-27 om 22 47 53" src="https://user-images.githubusercontent.com/33354141/119895142-bb3a4300-bf3d-11eb-9279-a0cc1a432129.png">

```
  - type: custom:auto-entities
    card:
      type: custom:badge-card
    filter:
      include:
        - domain: person
      exclude:
        - entity_id: person.*address
```

badges are showing fine btw.
