### ISSUE TITLE
Unable to apply icon to badge

### ISSUE THREAD

**Issue by dubilyer** [thomasloven/lovelace-badge-card#8]
Config:

```
 - type: custom:badge-card
        badges:
          - entity: media_player.s70pci
            icon: mdi:home
          - media_player.mibox4
          - switch.ebea7433149c9126c7vqfx
          - light.yeelight_ct_bulb_0x0000000007f29d50
          - switch.washer
        view_layout:
          grid-column-start: 1
          grid-column-end: 5
```

output html node:
```
<div class="badge-container">
    <div class="label-badge" id="badge">
        <div class="value big">
            <slot>
                <!--?lit$535976875$-->
                <!--?lit$535976875$--> <span><!--?lit$535976875$-->Выключен</span>
            </slot>
        </div>
        <!--?lit$535976875$-->
    </div>
    <!--?lit$535976875$-->
    <div class="title"><!--?lit$535976875$-->ТВ Салон</div>
</div>
```

Reflected in Lovelace UI: 

![by40t7bqh73k5hdux5tresczfbxwane0 ui nabu casa_lovelace_rooms](https://user-images.githubusercontent.com/16655093/124381737-c450c980-dccc-11eb-958b-60f74dc8efea.png)

**Comment by ildar170975** [comment]
I do not confirm this:
```
  - type: custom:badge-card
    badges:
      - entity: media_player.kodi_rpi_1
        icon: mdi:home
        name: xxxx
```
![изображение](https://user-images.githubusercontent.com/71872483/147117960-f6e1e16b-6e19-4967-98f9-24475451589a.png)
