### ISSUE TITLE
FR: add columns option

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-badge-card#9]
please consider adding a columns option (as on glance or grid) so we can do:L
```
- type: custom:badge-card
  columns: 5
  badges:
    - sensor.1_badge
    - sensor.2_badge
    - sensor.3_badge
    - sensor.4_badge
    - sensor.5_badge
    - sensor.6_badge
    - sensor.7_badge
    - sensor.8_badge
    - sensor.9_badge
    - sensor.10_badge
  ```

instead of:

```
entities:
  - type: custom:badge-card
    badges:
      - sensor.1_badge
      - sensor.2_badge
      - sensor.3_badge
      - sensor.4_badge
      - sensor.5_badge
  - type: custom:badge-card
    badges:
      - sensor.6_badge
      - sensor.7_badge
      - sensor.8_badge
      - sensor.9_badge
      - sensor.10_badge
```

thanks!

**Comment by Mariusthvdb** [comment]
given the new 2024.8 (!) badges, please reconsider this FR, it has become even more desirable to be able to do that.

see
```
type: custom:badge-card
badges:
  - entity: binary_sensor.donker_buiten
  - entity: sensor.buienradar_temperature
  - entity: sensor.buienradar_barometer
  - entity: sun.sun
```

and the result:

<img width="571" alt="Scherm­afbeelding 2024-08-01 om 11 57 39" src="https://github.com/user-attachments/assets/4107c5b4-d400-4de0-a9ca-b4f2de97326e">

Aware this has been somewhat neglected lately... but, given the new life for badges in modern HA and still not being able to place them anywhere but at the top of the views, I hope you will revisit this once more.

related HA documentation: https://rc.home-assistant.io/dashboards/badges/

this is a modern days replacement of the entities option in the OP
```
type: grid
square: false
columns: 4
cards:
  - type: custom:badge-card
    badges:
      - entity: binary_sensor.donker_buiten
  - type: custom:badge-card
    badges:
      - entity: sensor.buienradar_temperature
  - type: custom:badge-card
    badges:
      - entity: sensor.buienradar_barometer
  - type: custom:badge-card
    badges:
      - entity: sun.sun
```
<img width="436" alt="Scherm­afbeelding 2024-08-01 om 12 21 11" src="https://github.com/user-attachments/assets/0506c26b-b04f-4b2d-ad26-8094eefc9e59">


Thanks!
